/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReposRouteImport } from './routes/_authenticated/repos'
import { Route as AuthenticatedROwnerRepoRouteImport } from './routes/_authenticated/r.$owner.$repo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReposRoute = AuthenticatedReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedROwnerRepoRoute = AuthenticatedROwnerRepoRouteImport.update({
  id: '/r/$owner/$repo',
  path: '/r/$owner/$repo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/repos': typeof AuthenticatedReposRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$owner/$repo': typeof AuthenticatedROwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/repos': typeof AuthenticatedReposRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$owner/$repo': typeof AuthenticatedROwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/repos': typeof AuthenticatedReposRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/r/$owner/$repo': typeof AuthenticatedROwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/repos' | '/api/chat' | '/r/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/repos' | '/api/chat' | '/r/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/repos'
    | '/api/chat'
    | '/_authenticated/r/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repos': {
      id: '/_authenticated/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AuthenticatedReposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/r/$owner/$repo': {
      id: '/_authenticated/r/$owner/$repo'
      path: '/r/$owner/$repo'
      fullPath: '/r/$owner/$repo'
      preLoaderRoute: typeof AuthenticatedROwnerRepoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReposRoute: typeof AuthenticatedReposRoute
  AuthenticatedROwnerRepoRoute: typeof AuthenticatedROwnerRepoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReposRoute: AuthenticatedReposRoute,
  AuthenticatedROwnerRepoRoute: AuthenticatedROwnerRepoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
